### PR TITLE
also patch estraverse-fb - fixes #73

### LINKED ISSUE #73: Unknown node type ExportNamespaceSpecifier
`babel-eslint` fails to parse ES7 module exports (but compilation is OK):

```
> eslint src/ test/

/Users/fc/Development/ooflorent/parsly/node_modules/eslint/node_modules/estraverse/estraverse.js:511
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type ExportDefaultSpecifier.
    at Controller.traverse (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/node_modules/estraverse/estraverse.js:511:31)
    at EventEmitter.module.exports.api.verify (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/cli-engine.js:195:27)
    at /Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/cli-engine.js:295:26
    at /Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:83:9)
    at /Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
```

**index.js**

```js
export * as Parser from './parser'
export Transform from './transform'
```

**.babelrc**
```js
{
  "stage": 0,
  "loose": true
}
```

**.eslintrc**
```yml
---
parser: "babel-eslint"
env:
  es6: true
```

### PR DESCRIPTION
**Pull request by hzoo**
Was trying to get jscs working and got a similar error.

Not sure if this is right but eslint is also using estraverse at https://github.com/eslint/eslint/blob/master/lib/eslint.js#L11. Patching the keys for that reference of estraverse seems to fix the `Unknown node type ExportDefaultSpecifier` error.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -36,6 +36,10 @@ function monkeypatch() {
   estraverse = escopeMod.require("estraverse");
   assign(estraverse.VisitorKeys, t.VISITOR_KEYS);
 
+  // monkeypatch estraverse-fb
+  var estraverseFb = eslintMod.require('estraverse-fb');
```
Comment (sebmck) [inline index.js]: Double quotes please.

**Comment by hzoo** [comment]
And checking some of the other issues - it seems to fix #71, #81 for me.

File: index.js (hunk 1 above)
Comment (hzoo) [inline index.js]: oops

**Comment by sebmck** [comment]
Released as of 3.1.1, thanks!

**Comment by hzoo** [comment]
awesome.
